import styles from "./HowToUse.module.scss";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import BAYC_8817 from "../../assets/images/BAYC_8817.png";
import BAYC_1837 from "../../assets/images/BAYC_1837.png";
import BAYC_8585 from "../../assets/images/BAYC_8585.png";
import BAYC_2280 from "../../assets/images/BAYC_2280.png";
import BAYC_4160 from "../../assets/images/BAYC_4160.png";
import BAYC_5562 from "../../assets/images/BAYC_5562.png";
import slotConfig from "../../coinbet.config.json";

const HowToUse = () => {
  const [selectedTabIndex, setSelectedTabIndex] = useState(1);
  return (
    <>
      <div className={styles["how-to-use-wrapper"]}>
        <div className="container">
          <div className={styles["grid-container"]}>
            <div className={styles["tabs"]}>
              <h3
                className={selectedTabIndex === 1 ? styles["active"] : ""}
                onClick={() => setSelectedTabIndex(1)}
              >
                Players
              </h3>
              <h3
                className={selectedTabIndex === 0 ? styles["active"] : ""}
                onClick={() => setSelectedTabIndex(0)}
              >
                Rewards Providers
              </h3>
            </div>
            <div className={styles["tab-content"]}>
              {selectedTabIndex === 0 ? (
                <div className={styles["wrapper"]}>
                  <div>
                    <h3>What is a Coinbet House Pool?</h3>
                    <p>
                      In simple terms, a Coinbet House Pool is a liquidity pool where everyone can deposit funds to bankroll the betting activities of players playing our slot game. Participation in the pool allows you to earn yield from the volume generated by people who play the respective game. On the other side, the staked funds are used for paying rewards to the betters. Built on the concept of the RTP (Return to Player) ratio, the yield generated is a product of the RTP and the number of bets for a set timeframe.
                    </p>
                  </div>
                  <div>
                    <h3>How does it work?</h3>
                    <p>
                      Depositing funds to the Coinbet House Pool is straightforward. Navigate to the House Pool tab and click the Add Liquidity button. You’ll be prompted with the amount you wish to deposit. Then click Supply and voilà - you are now eligible to earn yield. Once you have deposited your funds, you’ll receive a Coinbet House Pool ERC20 token, representing your stake in the pool (in the same way you would provide liquidity to a Uniswap pool, but only with a single token).
                      <br></br>
                      <br></br>
                      You can open a liquidity position anytime during an epoch (each epoch is 1 week long). During the epoch, users can deposit funds, but can’t withdraw. The reason behind this is that the protocol needs to make sure that there will be funds available to pay any pending bets. (There is a 2-3 blocks window before the VRF function from Chainlink is settled after a bet is made).
                      <br></br>
                      <br></br>
                      Once the epoch has ended, there is a time window of 6 hours, when users can withdraw their funds safely. During this window, bets are not allowed and the house is closed. Once the withdrawal time window ends, we call the finalizeEpoch method and players can start betting again.
                    </p>
                  </div>
                  <div className={styles["example-list"]}>
                    <h3>Let’s take a look in this simplified example:</h3>
                    <p>
                      * You deposit 100 MATIC into the pool which has 900 MATIC already supplied. You receive a Coinbet House Pool token, representing that you now own 10% of the pool.
                    </p>
                    <p>
                      * After 1 week, you come back and the pool has grown from 1000 MATIC to 1100 MATIC (we assume, no additional reward providers have entered).
                    </p>
                    <p>
                      * Now your 10% stake equals 110 MATIC, which you can withdraw or claim just the difference (10 MATIC), by clicking Withdraw Liquidity and burning the Coinbet House Pool token.
                    </p>
                  </div>
                  <div>
                    <h3>Fees</h3>
                    <p>
                      To sustain itself, the Coinbet Protocol takes a small fee (4%) on the amount withdrawn from reward providers who exit the pool. This is also to incentivize reward providers to stay in the pool as long as possible to generate higher returns.
                      <br></br>
                      If a provider has more than 2000 $CFI at the moment of withdrawal, his/hers fee will be waived.
                    </p>
                  </div>
                  <div>
                    <h3>Future incentives</h3>
                    <p>
                      After the successful release, we plan to incentivize reward providers by creating a Yield Farming pool, where you can stake your Coinbet House Pool ERC20 token, and farm $CFI - the governance and utility token of the Coinbet Protocol. Stay tuned.
                    </p>
                  </div>
                  <div>
                    <h3>Security</h3>
                    <p>
                      Our smart contracts have been thoroughly tested and audited by high-ranking private auditors. The smart contract code can be checked through Etherscan, via the link provided in the Slot Game tab. However, please note this is an experimental technology and Coinbet does not take responsibility for any lost funds and smart contract bugs. It is important to note that, when you provide liquidity, in the short term it is possible to experience a deduction in your stake due to winning bets, so we advise you to leave your funds for at least a week. In other words, the generated yield grows proportionally to the number of bets taken.
                    </p>
                  </div>
                  <div>
                    <h3>Non-Affiliation Disclaimer</h3>
                    <p>
                      This web site is not endorsed by, directly affiliated with, maintained, authorized, or sponsored by Yuga Labs, Polygon Technologies and Chainlink Labs. All product and company names are the registered trademarks of their original owners. The use of any trade name or trademark is for identification and reference purposes only and does not imply any association with the trademark holder of their product brand.
                    </p>
                  </div>
                </div>
              ) : (
                <div className={styles["wrapper"]}>
                  <div>
                    <h3>What are Coinbet Slots?</h3>
                    <p>
                      Coinbet Slots is the first of many, truly permissionless and decentralized blockchain casino games powered by Coinbet. Players have full transparency regarding awarding prizes, using a protocol that runs on fair, transparent, and immutable smart contracts. The backbone of Coinbet’s games is Chainlink’s VRF (Verifiable Random Function), which feeds random numbers to the betting smart contracts. Users who play our games can be confident that their rewards will be paid out fully, as everything is enforced on a smart contract level.
                    </p>
                  </div>
                  <div>
                    <h3>How to play?</h3>
                    <p>
                      The Coinbet Slots game is very fun and easy to play. Just connect your wallet and your balance will be automatically detected. Currently, the minimum bet amount is 1 MATIC. The maximum bet amount depends on the funds in the Coinbet House Pool. Once you’re connected, just hit spin to move the slots and execute a transaction. Once the transaction is finished, your wallet will be directly credited in case your bet is winning.
                    </p>
                  </div>
                  <div>
                    <h3>Fees</h3>
                    <p>
                      To sustain itself, the Coinbet Slots game charges a small fee (2%) on each spin/bet.
                      <br></br>
                      If the player has more than 2000 $CFI at the moment of betting, his/hers fee will be waived.
                    </p>
                  </div>
                  <div>
                    <h3>Edge and RTP</h3>
                    <div className={styles["edge-rtp"]}>
                      <h3>
                        The RTP (Return to player) is {slotConfig.rtp}. Please see below the
                        multipliers:
                      </h3>
                      <div className={styles["grid"]}>
                        <div className={styles["column"]}>
                          <Image src={BAYC_8817} alt="BAYC #8817" />
                          <Image src={BAYC_8817} alt="BAYC #8817" />
                          <Image src={BAYC_8817} alt="BAYC #8817" />
                          <p>- x40 reward</p>
                        </div>
                        <div className={styles["column"]}>
                          <Image src={BAYC_8585} alt="BAYC #8585" />
                          <Image src={BAYC_8585} alt="BAYC #8585" />
                          <Image src={BAYC_8585} alt="BAYC #8585" />
                          <p>- x15 reward</p>
                        </div>
                        <div className={styles["column"]}>
                          <Image src={BAYC_5562} alt="BAYC #5562" />
                          <Image src={BAYC_5562} alt="BAYC #5562" />
                          <Image src={BAYC_5562} alt="BAYC #5562" />
                          <p>- x30 reward</p>
                        </div>
                        <div className={styles["column"]}>
                          <Image src={BAYC_4160} alt="BAYC #4160" />
                          <Image src={BAYC_4160} alt="BAYC #4160" />
                          <Image src={BAYC_4160} alt="BAYC #4160" />
                          <p>- x10 reward</p>
                        </div>
                        <div className={styles["column"]}>
                          <Image src={BAYC_2280} alt="BAYC #2280" />
                          <Image src={BAYC_2280} alt="BAYC #2280" />
                          <Image src={BAYC_2280} alt="BAYC #280" />
                          <p>- x20 reward</p>
                        </div>
                        <div className={styles["column"]}>
                          <Image src={BAYC_1837} alt="BAYC #1837" />
                          <Image src={BAYC_1837} alt="BAYC #1837" />
                          <Image src={BAYC_1837} alt="BAYC $1837" />
                          <p>- x5 reward</p>
                        </div>
                      </div>
                      <p>* Any two equal numbers - x1 reward</p>
                    </div>
                  </div>
                  <div>
                    <h3>Incentives</h3>
                    <p>
                      To incentivize the first players, on every spin 5 $CFI tokens will be credited to players, no matter if they have a winning or losing bet. The total amount of $CFI tokens that will be distributed as incentives is 5% of the total supply (across all Coinbet games).
                    </p>
                  </div>
                  <div>
                    <h3>Is it safe?</h3>
                    <p>
                      Coinbet Slots are perfectly safe to play. Our smart
                      contracts have been thoroughly tested and audited by
                      high-ranking private auditors and randomness is guaranteed
                      by Chainlink’s VRF. Moreover, no deposits are required -
                      you play and receive your winnings directly through your
                      wallet. We have multiple security checks to ensure that
                      when you place a bet, your reward will be fully paid. If
                      there is insufficient liquidity for rewards, the spin
                      won’t be executed.
                    </p>
                  </div>
                  <div>
                    <h3>Non-Affiliation Disclaimer</h3>
                    <p>
                      This web site is not endorsed by, directly affiliated with, maintained, authorized, or sponsored by Yuga Labs, Polygon Technologies and Chainlink Labs. All product and company names are the registered trademarks of their original owners. The use of any trade name or trademark is for identification and reference purposes only and does not imply any association with the trademark holder of their product brand.
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default HowToUse;
